apiVersion: v1
kind: Namespace
metadata:
  name: aiforce-test2
  labels:
    app.kubernetes.io/name: aiforce-test2
    app.kubernetes.io/part-of: aiforce
    app.kubernetes.io/managed-by: deployment-agent
