apiVersion: v1
kind: Secret
metadata:
  name: aiforce-test2-secrets
  namespace: aiforce-test2
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "<replace-with-base64-or-external-secret>"
  SECURITY_JWT_SECRET: "<replace-with-strong-32-byte-minimum-secret>"
